import numpy

In [14]:
import numpy as np


setting functions

In [64]:
board = np.zeros((6,6), int)
status = 0

def my_position(board, a):
    
    if (board[a,5] == 0):
        board[a,5] = x
    elif(board[a,4] == 0):
        board[a,4] = x
    elif(board[a,3] == 0):
        board[a,3] = x
    elif(board[a,2] == 0):
        board[a,2] = x
    elif(board[a,1] == 0):
        board[a,1] = x
    elif(board[a,0] == 0):
        board[a,0] = x
    return board

print(board)
while (status == 0):
    x = 1
    a = int(input("p turn"))
    # print (a)

    board = my_position(board, a)
    print("\n")
    print(board)
    


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


ValueError: invalid literal for int() with base 10: ''