import numpy

In [26]:
import numpy as np


setting functions

In [25]:
board = np.zeros((6,6), int)    # creat board with size of 6 by 6
status = 0


#--------------------------------------    position function    --------------------------------------

def my_position(board, a):  #inputs are board and given num from player
    
    global x
    a = a - 1

    if (board[5,a] == 0):
        board[5,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[4,a] == 0):
        board[4,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[3,a] == 0):
        board[3,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[2,a] == 0):
        board[2,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[1,a] == 0):
        board[1,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[0,a] == 0):
        board[0,a] = x
        x = (x % 2) + 1         # changing player number
    else:
        print ("try another number")
    return board

#------------------------------------    end of position function    --------------------------------------


#--------------------------------------    status check function    --------------------------------------

def status_check():
    
    global status

    for r in range (0,6):           # going to every row from 0 to 5 
        for c in range (0,4):       # checking 4 elements in row
            if (board[c,r] and board[c+1,r] and board[c+2,r] and board[c+3,r] == 1):
                status = 1
            elif (board[c,r] and board[c+1,r] and board[c+2,r] and board[c+3,r] == 2):
                status = 2
            else:
                status = 0
                
            return(status)
        
    for c in range (0,6):           # going to every column from 0 to 5 
        for r in range (0,4):       # checking 4 elements in row
            if (board[c,r] and board[c,r+1] and board[c,r+2] and board[c,r+3] == 1):
                status = 1
            elif (board[c,r] and board[c,r+1] and board[c,r+2] and board[c,r+3] == 2):
                status = 2
            else:
                status = 0
                
            return(status)
    

    for c in range (0,3):           # check in 45' for in order of moving from left to right and top to buttum
        for r in range (0,3):       
            if (board[c,r] and board[c+1,r+1] and board[c+2,r+2] and board[c+3,r+3] == 1):
                status = 1
            elif (board[c,r] and board[c+1,r+1] and board[c+2,r+2] and board[c+3,r+3] == 2):
                status = 2
            else:
                status = 0

            return(status)
            

    for c in range (5,2,-1):           # check in 45' for in order of moving from left to right and buttum to top
        for r in range (0,2):
            if (board[c,r] and board[c-1,r+1] and board[c-2,r+2] and board[c-3,r+3] ==1):                                
                status = 1
            elif (board[c,r] and board[c-1,r+1] and board[c-2,r+2] and board[c-3,r+3] ==2):
                status = 2
            else:
                status = 0

            return(status)
    
    return (status)

#-------------------------------------    end of status check function    --------------------------------------


#--------------------------------------    working area    --------------------------------------

print(board)    #print board for first time

x = 1
status = 0

while (status == 0):
    
    a = int(input())
    # print (a)

    if (0 < a < 7):

        board = my_position(board, a)
        print("\n")
        print(board)

        status = status_check()
        

    else:
        print ('try again')

if status != 0 :
    print("player " ,status, " win!!!!!!")




[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 2 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 1 2 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 1 2 2 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 1 2 2 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 1 2 2 2]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 1 2 2 2]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 2 0]
 [0 1 1 2 2 2]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 2 0]
 [0 1 1 2 2 2]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 2 0 

ValueError: invalid literal for int() with base 10: ''

In [30]:
board = np.zeros((6,6), int)    # creat board with size of 6 by 6
status = 0


#--------------------------------------    position function    --------------------------------------

def my_position(board, a):  #inputs are board and given num from player
    
    global x
    a = a - 1

    if (board[5,a] == 0):
        board[5,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[4,a] == 0):
        board[4,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[3,a] == 0):
        board[3,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[2,a] == 0):
        board[2,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[1,a] == 0):
        board[1,a] = x
        x = (x % 2) + 1         # changing player number
    elif(board[0,a] == 0):
        board[0,a] = x
        x = (x % 2) + 1         # changing player number
    else:
        print ("try another number")
    return board

#------------------------------------    end of position function    --------------------------------------


#--------------------------------------    status check function    --------------------------------------

def status_check():
    
    global status

    for c in range (0,6):           # going to every column from 0 to 5 
        for r in range (0,4):       # checking 4 elements in row
            if (board[c,r] and board[c,r+1] and board[c,r+2] and board[c,r+3] == 1):
                status = 1
            elif (board[c,r] and board[c,r+1] and board[c,r+2] and board[c,r+3] == 2):
                status = 2
            else:
                status = 0
                    
            return(status)
        

    
    return (status)

#-------------------------------------    end of status check function    --------------------------------------


#--------------------------------------    working area    --------------------------------------

print(board)    #print board for first time

x = 1
status = 0

while (status == 0):
    
    a = int(input())
    # print (a)

    if (0 < a < 7):

        board = my_position(board, a)
        print("\n")
        print(board)

        status = status_check()
        

    else:
        print ('try again')

if status != 0 :
    print("player " ,status, " win!!!!!!")




[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]]


[[0 0 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 0 0]
 [1 2 0 0 