import numpy

In [1]:
import numpy as np


setting functions

In [2]:
board = np.zeros((6,6), int)    # creat board with size of 6 by 6
status = 0

def my_position(board, a):  #inputs are board and given num from player
    
    if (board[a,5] == 0):
        board[a,5] = x
    elif(board[a,4] == 0):
        board[a,4] = x
    elif(board[a,3] == 0):
        board[a,3] = x
    elif(board[a,2] == 0):
        board[a,2] = x
    elif(board[a,1] == 0):
        board[a,1] = x
    elif(board[a,0] == 0):
        board[a,0] = x
    return board


def status_check():
    
    for j in range (0,6):           # going to every row from 0 to 5 
        for i in range (0,4):       # checking 4 elements in row
            if (board[i,j] == board[i+1,j] == board[i+2,j] == board[i+3,j] == 1):
        
                if(board[i,j] == 1):
                    status = 1
                elif(board[1,j] == 2):
                    status = 2
        
        for i in range (0,6):
            for j in range (0,4):
                if (board[i,j] == board[i,j+1] == board[i,j+2] == board[i,j+3] == 1):
                    
                    if(board[i,j] == 1):
                        status = 1
                    elif(board[1,j] == 2):
                        status = 2
    
                    print("player %i wins",status)






print(board)    #print board for first time

while (status == 0):
    x = 1
    a = int(input("p turn"))
    # print (a)

    board = my_position(board, a)
    print("\n")
    print(board)
    


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 1 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


ValueError: invalid literal for int() with base 10: ''